(() => {
  'use strict';
  const S=window.AVSync;if(!S)return;
  const ENDPOINT='wss://relay.justincreative.tech/ws',VIEWER_BASE='https://relay.justincreative.tech/';
  const PREFS_KEY='jcAvTimerRemoteLoginV3',PASS_KEY='jcAvTimerRemotePasswordV3',SEND_INTERVAL_MS=250,RECONNECT_MAX_MS=10000;
  const state={username:'',password:'',room:'',token:'',socket:null,socketState:'offline',connections:0,reconnectAttempt:0,reconnectTimer:null,manualClose:true,pendingPayload:null,sendTimer:null,lastSendAt:0,lastError:''};
  const el={topStatus:document.getElementById('cloudTopStatus')};

  function loadPrefs(){try{const saved=JSON.parse(localStorage.getItem(PREFS_KEY)||'null');state.username=String(saved?.username||'').slice(0,64);state.password=String(sessionStorage.getItem(PASS_KEY)||'').slice(0,128)}catch{}}
  function savePrefs(){try{localStorage.setItem(PREFS_KEY,JSON.stringify({username:state.username}));if(state.password)sessionStorage.setItem(PASS_KEY,state.password);else sessionStorage.removeItem(PASS_KEY)}catch{}}
  function canonicalUsername(v){return String(v||'').normalize('NFKC').trim().toLowerCase()}
  function utf8Bytes(value){
    const out=[]; const str=String(value === null || value === undefined ? '' : value);
    for(let i=0;i<str.length;i++){
      let cp=str.charCodeAt(i);
      if(cp>=0xD800&&cp<=0xDBFF&&i+1<str.length){const lo=str.charCodeAt(i+1);if(lo>=0xDC00&&lo<=0xDFFF){cp=0x10000+((cp-0xD800)<<10)+(lo-0xDC00);i++;}}
      if(cp<=0x7F) out.push(cp);
      else if(cp<=0x7FF) out.push(0xC0|(cp>>6),0x80|(cp&63));
      else if(cp<=0xFFFF) out.push(0xE0|(cp>>12),0x80|((cp>>6)&63),0x80|(cp&63));
      else out.push(0xF0|(cp>>18),0x80|((cp>>12)&63),0x80|((cp>>6)&63),0x80|(cp&63));
    }
    return out;
  }
  function sha256Fallback(value){
    const bytes=utf8Bytes(value), words=[]; const bitLen=bytes.length*8;
    for(let i=0;i<bytes.length;i++) words[i>>2]=(words[i>>2]||0)|(bytes[i]<<(24-(i%4)*8));
    words[bitLen>>5]=(words[bitLen>>5]||0)|(0x80<<(24-(bitLen%32)));
    words[(((bitLen+64)>>9)<<4)+15]=bitLen;
    const K=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];
    let H=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19];
    const rotr=(x,n)=>(x>>>n)|(x<<(32-n));
    for(let off=0;off<words.length;off+=16){
      const w=new Array(64); for(let i=0;i<16;i++) w[i]=words[off+i]|0;
      for(let i=16;i<64;i++){const a=w[i-15],b=w[i-2],s0=rotr(a,7)^rotr(a,18)^(a>>>3),s1=rotr(b,17)^rotr(b,19)^(b>>>10);w[i]=(w[i-16]+s0+w[i-7]+s1)|0;}
      let [a,b,c,d,e,f,g,h]=H;
      for(let i=0;i<64;i++){const S1=rotr(e,6)^rotr(e,11)^rotr(e,25),ch=(e&f)^((~e)&g),t1=(h+S1+ch+K[i]+w[i])|0,S0=rotr(a,2)^rotr(a,13)^rotr(a,22),maj=(a&b)^(a&c)^(b&c),t2=(S0+maj)|0;h=g;g=f;f=e;e=(d+t1)|0;d=c;c=b;b=a;a=(t1+t2)|0;}
      H=[(H[0]+a)|0,(H[1]+b)|0,(H[2]+c)|0,(H[3]+d)|0,(H[4]+e)|0,(H[5]+f)|0,(H[6]+g)|0,(H[7]+h)|0];
    }
    return H.map(x=>(x>>>0).toString(16).padStart(8,'0')).join('');
  }
  async function sha256Hex(value){
    try{
      if(typeof window !== 'undefined' && window.crypto && window.crypto.subtle && typeof TextEncoder !== 'undefined'){
        const data=new TextEncoder().encode(String(value));
        const digest=await crypto.subtle.digest('SHA-256',data);
        return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');
      }
    }catch{}
    return sha256Fallback(value);
  }
  async function deriveCredentials(username,password){const user=canonicalUsername(username),pass=String(password||'');if(user.length<3)throw new Error('Username must be at least 3 characters.');if(pass.length<4)throw new Error('Password must be at least 4 characters.');if(user.length>64||pass.length>128)throw new Error('Username or password is too long.');const roomHash=await sha256Hex(`jc-av-timer-room-v2\u0000${user}\u0000${pass}`),token=await sha256Hex(`jc-av-timer-token-v2\u0000${user}\u0000${pass}`);return{room:`VIEW-${roomHash.slice(0,24).toUpperCase()}`,token}}
  function viewerLink(){const user=state.username.trim();if(!user)return VIEWER_BASE;const url=new URL(VIEWER_BASE);url.searchParams.set('user',user);return url.toString()}
  function isConnected(){return state.socket&&state.socket.readyState===WebSocket.OPEN&&state.socketState==='online'}
  function viewerCount(){return Math.max(0,Number(state.connections||0)-1)}

  function injectStyles(){if(document.getElementById('cloudSyncStyles'))return;const style=document.createElement('style');style.id='cloudSyncStyles';style.textContent=`.cloud-sync-body{display:flex;flex-direction:column;gap:7px}.cloud-status-row{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;border:1px solid var(--line);background:#0b1726;border-radius:9px;padding:8px 9px}.cloud-status-main{display:flex;align-items:center;gap:8px;min-width:0}.cloud-dot{width:8px;height:8px;border-radius:50%;background:#64748b}.cloud-dot.online{background:#22c55e}.cloud-dot.connecting{background:#f59e0b}.cloud-dot.offline{background:#ef4444}.cloud-status-text strong{display:block;font-size:.74rem}.cloud-status-text span{display:block;color:var(--muted);font-size:.66rem}.cloud-peer-count{font-size:.68rem;color:#b8daf1}.cloud-field{display:flex;flex-direction:column;gap:4px}.cloud-field>span{font-size:.68rem;color:var(--muted);font-weight:800}.cloud-field input{width:100%;background:#0a1422;border:1px solid #30445f;color:var(--fg);border-radius:8px;padding:8px 9px;outline:none}.cloud-password-wrap,.cloud-copy-wrap{display:grid;grid-template-columns:1fr auto;gap:6px}.cloud-action-row{display:grid;grid-template-columns:1fr 1fr;gap:6px}.cloud-action-row.single{grid-template-columns:1fr}.cloud-connect-btn{background:#138a4e;border-color:#22c55e;font-weight:850}.cloud-disconnect-btn{background:#53262c;border-color:#8a3942}.cloud-note{font-size:.68rem;line-height:1.4;color:var(--muted);margin:0}.cloud-credentials-card{border:1px solid rgba(75,183,255,.28);background:rgba(14,49,75,.25);border-radius:9px;padding:8px;display:flex;flex-direction:column;gap:6px}.cloud-credentials-card.hidden{display:none}`;document.head.appendChild(style)}

  function injectUI(){injectStyles();const anchor=document.getElementById('remoteViewerAnchor');if(!anchor)return;anchor.className='panel cloud-sync-panel';anchor.innerHTML=`<div class="panel-title-row"><div><div class="panel-kicker">INTERNET</div><h2>Remote Viewer</h2></div><div class="inline-heading-actions"><span id="cloudPanelPill" class="status-pill idle">Offline</span><button class="panel-help" id="cloudHelpBtn">?</button></div></div><div class="cloud-sync-body"><div class="cloud-status-row"><div class="cloud-status-main"><span id="cloudStatusDot" class="cloud-dot offline"></span><div class="cloud-status-text"><strong id="cloudStatusTitle">Remote viewer offline</strong><span id="cloudStatusDetail">Not connected</span></div></div><span id="cloudPeerCount" class="cloud-peer-count">0 viewers</span></div><label class="cloud-field"><span>Username</span><input id="cloudUsername" type="text" maxlength="64" autocomplete="username" spellcheck="false" placeholder="User"></label><label class="cloud-field"><span>Password</span><div class="cloud-password-wrap"><input id="cloudPassword" type="password" maxlength="128" autocomplete="new-password" placeholder="Password"><button id="cloudShowPassword" type="button">Show</button></div></label><div class="cloud-action-row single"><button id="cloudStartHost" type="button" class="cloud-connect-btn">Start Remote Viewer</button></div><div id="cloudShareCard" class="cloud-credentials-card hidden"><label class="cloud-field"><span>Viewer link</span><div class="cloud-copy-wrap"><input id="cloudViewerLink" type="text" readonly><button id="cloudCopyLink" type="button">Copy</button></div></label><div class="cloud-action-row"><button id="cloudCopyLogin" type="button">Copy Login</button><button id="cloudDisconnect" type="button" class="cloud-disconnect-btn">Stop Hosting</button></div></div><p class="cloud-note">Share this timer with another device over the internet. Viewers open <strong>relay.justincreative.tech</strong> and enter the same username/password.</p></div>`;
    Object.assign(el,{panelPill:document.getElementById('cloudPanelPill'),username:document.getElementById('cloudUsername'),password:document.getElementById('cloudPassword'),showPassword:document.getElementById('cloudShowPassword'),startHost:document.getElementById('cloudStartHost'),shareCard:document.getElementById('cloudShareCard'),viewerLink:document.getElementById('cloudViewerLink'),copyLink:document.getElementById('cloudCopyLink'),copyLogin:document.getElementById('cloudCopyLogin'),disconnect:document.getElementById('cloudDisconnect'),dot:document.getElementById('cloudStatusDot'),statusTitle:document.getElementById('cloudStatusTitle'),statusDetail:document.getElementById('cloudStatusDetail'),peerCount:document.getElementById('cloudPeerCount')});
    el.username.value=state.username;el.password.value=state.password;el.startHost.onclick=startHost;el.disconnect.onclick=disconnectHost;el.showPassword.onclick=()=>{const show=el.password.type==='password';el.password.type=show?'text':'password';el.showPassword.textContent=show?'Hide':'Show'};el.username.oninput=()=>{state.username=el.username.value.trim().slice(0,64);savePrefs();el.viewerLink.value=viewerLink()};el.password.oninput=()=>{state.password=el.password.value.slice(0,128);savePrefs()};el.copyLink.onclick=()=>copyText(viewerLink(),el.copyLink);el.copyLogin.onclick=()=>copyText(`AV Timer Viewer\n${viewerLink()}\nUsername: ${state.username}\nPassword: ${state.password}`,el.copyLogin);document.getElementById('cloudHelpBtn').onclick=()=>document.querySelector('[data-help-target="remote-help"]')?.click();render()}

  function render(){if(!el.panelPill)return;const connected=isConnected(),busy=['connecting','reconnecting'].includes(state.socketState),viewers=viewerCount();el.shareCard.classList.toggle('hidden',!connected&&!busy);el.username.disabled=connected||busy;el.password.disabled=connected||busy;el.showPassword.disabled=connected||busy;el.startHost.disabled=connected||busy;el.startHost.textContent=connected?'Remote Viewer Running':busy?'Connecting…':'Start Remote Viewer';el.viewerLink.value=viewerLink();let short='Offline',title='Remote viewer offline',detail='Enter a username and password to start hosting',cls='idle';if(connected){short=`Remote · ${viewers}`;title='Remote viewer connected';detail=state.username?`Login: ${state.username}`:'Connected';cls='online'}else if(busy){short='Connecting';title=state.socketState==='reconnecting'?'Reconnecting':'Connecting to relay';detail='Opening secure WebSocket…';cls='paused'}else if(state.lastError){detail=state.lastError;cls='offline'}if(el.topStatus){el.topStatus.textContent=connected?`Remote · ${viewers}`:busy?'Remote connecting':'Remote offline';el.topStatus.className=`status-pill ${cls}`;}el.panelPill.textContent=short;el.panelPill.className=`status-pill ${cls}`;el.statusTitle.textContent=title;el.statusDetail.textContent=detail;el.dot.className=`cloud-dot ${connected?'online':busy?'connecting':'offline'}`;el.peerCount.textContent=`${viewers} viewer${viewers===1?'':'s'}`;window.dispatchEvent(new CustomEvent('av-cloud-status',{detail:{connected,connections:state.connections,viewers}}))}
  async function startHost(){state.username=el.username.value.trim().slice(0,64);state.password=el.password.value.slice(0,128);savePrefs();state.lastError='';try{const d=await deriveCredentials(state.username,state.password);connectHost(d.room,d.token)}catch(err){state.socketState='offline';state.lastError=err?.message||'Could not create remote login.';render()}}
  function connectHost(room,token){disconnect(false);state.room=room;state.token=token;state.manualClose=false;state.socketState='connecting';state.lastError='';render();const url=new URL(ENDPOINT);url.searchParams.set('room',room);url.searchParams.set('role','host');url.searchParams.set('token',token);url.searchParams.set('name',state.username||'Host');let ws;try{ws=new WebSocket(url.toString())}catch(err){state.socketState='offline';state.lastError=err?.message||'Could not open WebSocket.';render();return}state.socket=ws;ws.onopen=()=>{if(state.socket!==ws)return;state.socketState='online';state.reconnectAttempt=0;state.lastError='';render();queueHostPayload(S.getCached(),true)};ws.onmessage=e=>{if(state.socket!==ws)return;let p;try{p=JSON.parse(e.data)}catch{return}if(p.type==='welcome'||p.type==='presence'){state.connections=Math.max(0,Number(p.connections||1));render();if(p.type==='welcome')queueHostPayload(S.getCached(),true)}else if(p.type==='error'){state.lastError=p.message||p.code||'Relay error';render()}};ws.onerror=()=>{state.lastError='Relay connection error'};ws.onclose=e=>{if(state.socket!==ws)return;state.socket=null;state.connections=0;if(state.manualClose){state.socketState='offline';render();return}if(e.code===4001){state.manualClose=true;state.socketState='offline';state.lastError='Another host signed in with the same username/password.';render();return}scheduleReconnect()}}
  function disconnect(manual=true){if(state.reconnectTimer)clearTimeout(state.reconnectTimer);state.reconnectTimer=null;state.manualClose=manual;const ws=state.socket;state.socket=null;state.connections=0;state.socketState='offline';if(ws)try{ws.close(1000,'Disconnected')}catch{}if(state.sendTimer)clearTimeout(state.sendTimer);state.sendTimer=null;state.pendingPayload=null;if(manual)state.lastError=''}
  function disconnectHost(){disconnect(true);render()}
  function scheduleReconnect(){state.socketState='reconnecting';render();const delay=Math.min(RECONNECT_MAX_MS,1000*Math.pow(1.7,state.reconnectAttempt++));state.reconnectTimer=setTimeout(()=>{state.reconnectTimer=null;if(!state.manualClose&&state.room&&state.token)connectHost(state.room,state.token)},delay)}
  function safeSend(p){if(!isConnected())return false;try{state.socket.send(JSON.stringify(p));return true}catch{return false}}
  function queueHostPayload(payload,immediate=false){if(!payload)return;state.pendingPayload=payload;if(!isConnected()||state.sendTimer)return;const elapsed=Date.now()-state.lastSendAt,wait=immediate?0:Math.max(0,SEND_INTERVAL_MS-elapsed);state.sendTimer=setTimeout(flushHostPayload,wait)}
  function flushHostPayload(){state.sendTimer=null;if(!state.pendingPayload||!isConnected())return;const payload=state.pendingPayload;state.pendingPayload=null;if(safeSend({type:'state',data:payload}))state.lastSendAt=Date.now();if(state.pendingPayload)queueHostPayload(state.pendingPayload)}
  async function copyText(text,button){if(!text)return;try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent='Copied';setTimeout(()=>button.textContent=old,1000)}catch{window.prompt('Copy this:',text)}}

  S.onState(payload=>{if(isConnected()||state.socketState==='connecting'||state.socketState==='reconnecting')queueHostPayload(payload)},false);window.addEventListener('online',()=>{if(!isConnected()&&!state.manualClose&&state.room&&state.token)scheduleReconnect()});window.addEventListener('beforeunload',()=>disconnect(true));loadPrefs();injectUI();
  window.AVCloudSync={endpoint:ENDPOINT,startHost,disconnect:disconnectHost,deriveCredentials,getState:()=>({username:state.username,status:state.socketState,connections:state.connections,viewers:viewerCount(),connected:isConnected(),viewerLink:viewerLink()})};
})();
